version: '3'
services:
  gnpslibrary-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpslibrary-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    ports:
    - "6548:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh


networks:
  nginx-net:
    external:
      name: nginx-net