version: '3'
services:
  gnpslcms-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpslcms-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp
    ports:
    - "6548:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh


networks:
  nginx-net:
    external:
      name: nginx-net