version: '3'
services:
  gnpslcms-dash:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: gnpslcms-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp
    ports:
    - "6548:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: ${HOSTNAME:-gnps-lcms.gnps2.org}
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: ${HOSTNAME:-gnps-lcms.gnps2.org}
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    deploy:
      resources:
        limits:
          memory: 32000M
      
  gnpslcms-worker-conversion:
    build:
      context: .
      dockerfile: Dockerfile.conversion
    container_name: gnpslcms-worker-conversion
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp
    command: /app/run_worker_conversion.sh
    restart: unless-stopped
    depends_on: 
      - gnpslcms-redis
    networks:
      - default
      - nginx-net
    deploy:
      resources:
        limits:
          memory: 32000M

  gnpslcms-worker-compute:
    build:
      context: .
      dockerfile: Dockerfile.compute
    container_name: gnpslcms-worker-compute
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
      - ./feature_finding:/app/feature_finding:ro
    command: /app/run_worker_compute.sh
    restart: unless-stopped
    depends_on: 
      - gnpslcms-redis
    networks:
      - default
      - nginx-net
    deploy:
      resources:
        limits:
          memory: 32000M

  gnpslcms-worker-featurefinding:
    build:
      context: .
      dockerfile: Dockerfile.featurefinding
    container_name: gnpslcms-worker-featurefinding
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
      - ./feature_finding:/app/feature_finding:ro
    command: /app/run_worker_featurefinding.sh
    restart: unless-stopped
    depends_on: 
      - gnpslcms-redis
    networks:
      - default
      - nginx-net
    deploy:
      resources:
        limits:
          memory: 32000M

  gnpslcms-worker-sync:
    build:
      context: .
      dockerfile: Dockerfile.dash
    container_name: gnpslcms-worker-sync
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    command: /app/run_worker_sync.sh
    restart: unless-stopped
    depends_on: 
      - gnpslcms-redis
    networks:
      - default
      - nginx-net
    deploy:
      resources:
        limits:
          memory: 32000M

  gnpslcms-redis:
    image: redis
    restart: unless-stopped
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 8000M

networks:
  nginx-net:
    external: true