FROM ubuntu:22.04
MAINTAINER Mingxun Wang "mwang87@gmail.com"

################## INSTALLATION ######################
RUN apt-get update && apt-get install -y git lftp libarchive-dev libhdf5-serial-dev netcdf-bin libnetcdf-dev wget

# Install Mamba
ENV CONDA_DIR /opt/conda
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O ~/miniforge.sh && /bin/bash ~/miniforge.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# Adding to bashrc
RUN echo "export PATH=$CONDA_DIR:$PATH" >> ~/.bashrc

# Forcing version of Python
RUN mamba create -n py311 python=3.10 -y

COPY requirements-featurefinding.txt .
RUN /bin/bash -c 'source activate py311 && pip install -r requirements-featurefinding.txt'

# Installing MassQL
RUN /bin/bash -c 'source activate py311 && pip install git+https://github.com/mwang87/MassQueryLanguage.git'

# Installing Java
RUN mamba install -c conda-forge -y openjdk=11.0.9.1 -n py311

# Datashader
RUN mamba install -c conda-forge -y datashader -n py311


COPY . /app
WORKDIR /app

