version: '3'
services:
  gnpslcms-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpslcms-dash
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp
    ports:
    - "6548:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: gnps-lcms.ucsd.edu
      VIRTUAL_PORT: 6548
      LETSENCRYPT_HOST: gnps-lcms.ucsd.edu
      LETSENCRYPT_EMAIL: miw023@ucsd.edu

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpslcms-worker
    volumes:
      - ./output:/app/output:rw
      - ./logs:/app/logs:rw
      - ./temp:/app/temp
    command: /app/run_worker.sh
    restart: unless-stopped
    depends_on: 
      - redis
    networks:
      - default
      - nginx-net

  redis:
    image: redis
    networks:
      - default

networks:
  nginx-net:
    external:
      name: nginx-net