FROM ubuntu:22.04
MAINTAINER Mingxun Wang "mwang87@gmail.com"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git lftp libarchive-dev wget vim mono-devel libhdf5-serial-dev netcdf-bin libnetcdf-dev

# Install Mamba
ENV CONDA_DIR /opt/conda
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O ~/miniforge.sh && /bin/bash ~/miniforge.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# Adding to bashrc
RUN echo "export PATH=$CONDA_DIR:$PATH" >> ~/.bashrc

################## METADATA ######################
LABEL base_image="mono:latest"
LABEL version="1"
LABEL software="ThermoRawFileParser"
LABEL software.version="1.0.0"
LABEL about.summary="A software to convert Thermo RAW files to mgf and mzML"
LABEL about.home="https://github.com/compomics/ThermoRawFileParser"
LABEL about.documentation="https://github.com/compomics/ThermoRawFileParser"
LABEL about.license_file="https://github.com/compomics/ThermoRawFileParser"
LABEL about.license="SPDX:Unknown"
LABEL about.tags="Proteomics"

################## INSTALLATION OF MONO ######################
RUN apt-get update && apt -y install apt-transport-https dirmngr gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/debian stable-buster main" | tee /etc/apt/sources.list.d/mono-official-stable.list

WORKDIR /src
RUN git clone -b master --single-branch https://github.com/compomics/ThermoRawFileParser --branch v1.3.2 /src
RUN xbuild

COPY requirements-conversion.txt .
RUN pip install -r requirements-conversion.txt


# Install Aspera
# RUN wget -qO- https://ak-delivery04-mul.dhe.ibm.com/sar/CMA/OSA/0a07f/0/ibm-aspera-connect_4.1.0.46-linux_x86_64.tar.gz | tar xvz
# RUN chmod +x ibm-aspera-connect_4.1.0.46-linux_x86_64.sh
# RUN ./ibm-aspera-connect_4.1.0.46-linux_x86_64.sh

# Datashader
RUN mamba install -c conda-forge -y datashader
RUN pip install dask[complete]

COPY . /app
WORKDIR /app

