name: loadtest

on:
  - push
  - pull_request
  #schedule:
  # - cron:  '*/60 * * * *'

jobs:
  load-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
# TODO: We probably should switch to using the Docker version.
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Docker
      run: |
        docker ps
